import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Tiny Link",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white">
        <ThemeProvider>

          <header className="sticky top-0 z-50">
            <Navbar />
          </header>

          <main className="max-w-6xl mx-auto w-full p-4 flex-1">
            <Toaster richColors />
            {children}

          </main>

          {/* <footer className="bg-white border-t sticky bottom-0 z-50">
          <Footer/>
          </footer> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
